name: Deploy With GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
